### ISSUE TITLE
Server-Management

### ISSUE THREAD

**Issue by SebastianOpriel** [DeemOpen/excord#7]
Hello,

thanks for your work! 
I suggest one thing: Add a "manage" section to the frontend where you can shutdown the server and see the health statistics.
Or at least: Allow a GET-Request for the shutdown url. Many people may not have curl installed locally.

Kind regards
Bastian

**Comment by gitorko** [comment]
Thanks for supporting the tool. 
The shutdown and health statistics are provided by default spring boot frame work. They can be hit via any restclient tool/plugin in browser apart from curl command line.
